## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
from sklearn.model_selection import train_test_split, KFold
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [3]:
# 將資料切分為 y=0 及 y=1 兩個類別
mask = (y==1)
X_y1, y_y1 = X[mask], y[mask]
X_y0, y_y0 = X[~mask], y[~mask]

In [4]:
#使用 train_test_split 函數進行切分
size = y_y1.size
X_y1_train, X_y1_test, y_y1_train, y_y1_test = train_test_split(X_y1, y_y1, test_size=(10/size))

size = y_y0.size
X_y0_train, X_y0_test, y_y0_train, y_y0_test = train_test_split(X_y0, y_y0, test_size=(10/size))

# 合併 y=0 及 y=1 兩個類別的 train/test data
X_train = np.concatenate((X_y1_train, X_y0_train), axis=0)
y_train = np.concatenate((y_y1_train, y_y0_train), axis=0)

X_test = np.concatenate((X_y1_test, X_y0_test), axis=0)
y_test = np.concatenate((y_y1_test, y_y0_test), axis=0)

In [5]:
X_test

array([[160, 161, 162, 163, 164],
       [ 50,  51,  52,  53,  54],
       [135, 136, 137, 138, 139],
       [ 20,  21,  22,  23,  24],
       [ 60,  61,  62,  63,  64],
       [165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174],
       [ 80,  81,  82,  83,  84],
       [175, 176, 177, 178, 179],
       [ 65,  66,  67,  68,  69],
       [475, 476, 477, 478, 479],
       [615, 616, 617, 618, 619],
       [425, 426, 427, 428, 429],
       [575, 576, 577, 578, 579],
       [370, 371, 372, 373, 374],
       [500, 501, 502, 503, 504],
       [295, 296, 297, 298, 299],
       [335, 336, 337, 338, 339],
       [995, 996, 997, 998, 999],
       [325, 326, 327, 328, 329]])

In [6]:
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])